# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/P4MK2/p4mk2/p4mk2.cache/wt [current_project]
set_property parent.project_path C:/P4MK2/p4mk2/p4mk2.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:cora-z7-10:part0:1.0 [current_project]
set_property ip_repo_paths c:/ip_repo [current_project]
update_ip_catalog
set_property ip_output_repo c:/P4MK2/p4mk2/p4mk2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/P4MK2/p4mk2/p4mk2.srcs/sources_1/bd/dgn/ip/initial_color.coe
read_vhdl -library xil_defaultlib C:/P4MK2/p4mk2/p4mk2.srcs/sources_1/bd/dgn/hdl/dgn_wrapper.vhd
add_files C:/P4MK2/p4mk2/p4mk2.srcs/sources_1/bd/dgn/dgn.bd
set_property used_in_implementation false [get_files -all c:/P4MK2/p4mk2/p4mk2.srcs/sources_1/bd/dgn/ip/dgn_slv_0_0/src/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/P4MK2/p4mk2/p4mk2.srcs/sources_1/bd/dgn/ip/dgn_clk_wiz_1/dgn_clk_wiz_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/P4MK2/p4mk2/p4mk2.srcs/sources_1/bd/dgn/ip/dgn_clk_wiz_1/dgn_clk_wiz_1.xdc]
set_property used_in_implementation false [get_files -all c:/P4MK2/p4mk2/p4mk2.srcs/sources_1/bd/dgn/ip/dgn_clk_wiz_1/dgn_clk_wiz_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/P4MK2/p4mk2/p4mk2.srcs/sources_1/bd/dgn/ip/dgn_rst_clk_wiz_100M_4/dgn_rst_clk_wiz_100M_4_board.xdc]
set_property used_in_implementation false [get_files -all c:/P4MK2/p4mk2/p4mk2.srcs/sources_1/bd/dgn/ip/dgn_rst_clk_wiz_100M_4/dgn_rst_clk_wiz_100M_4.xdc]
set_property used_in_implementation false [get_files -all C:/P4MK2/p4mk2/p4mk2.srcs/sources_1/bd/dgn/dgn_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/P4MK2/p4mk2/p4mk2.srcs/constrs_1/imports/ip_repo/VGA_constr.xdc
set_property used_in_implementation false [get_files C:/P4MK2/p4mk2/p4mk2.srcs/constrs_1/imports/ip_repo/VGA_constr.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top dgn_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef dgn_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file dgn_wrapper_utilization_synth.rpt -pb dgn_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
