# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/ip_repo/VGA_constr.xdc

# Block Designs: bd/dgn/dgn.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dgn || ORIG_REF_NAME==dgn} -quiet] -quiet

# IP: bd/dgn/ip/dgn_videomemlab_0_0/dgn_videomemlab_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dgn_videomemlab_0_0 || ORIG_REF_NAME==dgn_videomemlab_0_0} -quiet] -quiet

# IP: bd/dgn/ip/dgn_kybd_slv_0_0/dgn_kybd_slv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dgn_kybd_slv_0_0 || ORIG_REF_NAME==dgn_kybd_slv_0_0} -quiet] -quiet

# IP: bd/dgn/ip/dgn_slv_0_0/dgn_slv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dgn_slv_0_0 || ORIG_REF_NAME==dgn_slv_0_0} -quiet] -quiet

# IP: bd/dgn/ip/dgn_slv_0_0/src/blk_mem_gen_0_1/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: bd/dgn/ip/dgn_clk_wiz_1/dgn_clk_wiz_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dgn_clk_wiz_1 || ORIG_REF_NAME==dgn_clk_wiz_1} -quiet] -quiet

# IP: bd/dgn/ip/dgn_xbar_6/dgn_xbar_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dgn_xbar_6 || ORIG_REF_NAME==dgn_xbar_6} -quiet] -quiet

# IP: bd/dgn/ip/dgn_videomemlab_0_axi_periph_6/dgn_videomemlab_0_axi_periph_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dgn_videomemlab_0_axi_periph_6 || ORIG_REF_NAME==dgn_videomemlab_0_axi_periph_6} -quiet] -quiet

# IP: bd/dgn/ip/dgn_rst_clk_wiz_100M_4/dgn_rst_clk_wiz_100M_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dgn_rst_clk_wiz_100M_4 || ORIG_REF_NAME==dgn_rst_clk_wiz_100M_4} -quiet] -quiet

# XDC: bd/dgn/ip/dgn_slv_0_0/src/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc

# XDC: bd/dgn/ip/dgn_clk_wiz_1/dgn_clk_wiz_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dgn_clk_wiz_1 || ORIG_REF_NAME==dgn_clk_wiz_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/dgn/ip/dgn_clk_wiz_1/dgn_clk_wiz_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dgn_clk_wiz_1 || ORIG_REF_NAME==dgn_clk_wiz_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/dgn/ip/dgn_clk_wiz_1/dgn_clk_wiz_1_ooc.xdc

# XDC: bd/dgn/ip/dgn_rst_clk_wiz_100M_4/dgn_rst_clk_wiz_100M_4_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dgn_rst_clk_wiz_100M_4 || ORIG_REF_NAME==dgn_rst_clk_wiz_100M_4} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/dgn/ip/dgn_rst_clk_wiz_100M_4/dgn_rst_clk_wiz_100M_4.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dgn_rst_clk_wiz_100M_4 || ORIG_REF_NAME==dgn_rst_clk_wiz_100M_4} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/dgn/dgn_ooc.xdc
