# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/p4/VGA_constr.xdc

# Block Designs: bd/dgn_1/dgn_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dgn_1 || ORIG_REF_NAME==dgn_1} -quiet] -quiet

# IP: bd/dgn_1/ip/dgn_1_videomemlab_0_axi_periph_0/dgn_1_videomemlab_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dgn_1_videomemlab_0_axi_periph_0 || ORIG_REF_NAME==dgn_1_videomemlab_0_axi_periph_0} -quiet] -quiet

# IP: bd/dgn_1/ip/dgn_1_clk_wiz_0/dgn_1_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dgn_1_clk_wiz_0 || ORIG_REF_NAME==dgn_1_clk_wiz_0} -quiet] -quiet

# IP: bd/dgn_1/ip/dgn_1_rst_clk_wiz_100M_0/dgn_1_rst_clk_wiz_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dgn_1_rst_clk_wiz_100M_0 || ORIG_REF_NAME==dgn_1_rst_clk_wiz_100M_0} -quiet] -quiet

# IP: bd/dgn_1/ip/dgn_1_slv_0_2/dgn_1_slv_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dgn_1_slv_0_2 || ORIG_REF_NAME==dgn_1_slv_0_2} -quiet] -quiet

# IP: bd/dgn_1/ip/dgn_1_slv_0_2/src/blk_mem_gen_0_1/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: bd/dgn_1/ip/dgn_1_videomemlab_0_1/dgn_1_videomemlab_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dgn_1_videomemlab_0_1 || ORIG_REF_NAME==dgn_1_videomemlab_0_1} -quiet] -quiet

# XDC: bd/dgn_1/ip/dgn_1_clk_wiz_0/dgn_1_clk_wiz_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dgn_1_clk_wiz_0 || ORIG_REF_NAME==dgn_1_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/dgn_1/ip/dgn_1_clk_wiz_0/dgn_1_clk_wiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dgn_1_clk_wiz_0 || ORIG_REF_NAME==dgn_1_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/dgn_1/ip/dgn_1_clk_wiz_0/dgn_1_clk_wiz_0_ooc.xdc

# XDC: bd/dgn_1/ip/dgn_1_rst_clk_wiz_100M_0/dgn_1_rst_clk_wiz_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dgn_1_rst_clk_wiz_100M_0 || ORIG_REF_NAME==dgn_1_rst_clk_wiz_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/dgn_1/ip/dgn_1_rst_clk_wiz_100M_0/dgn_1_rst_clk_wiz_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dgn_1_rst_clk_wiz_100M_0 || ORIG_REF_NAME==dgn_1_rst_clk_wiz_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/dgn_1/ip/dgn_1_slv_0_2/src/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc

# XDC: bd/dgn_1/dgn_1_ooc.xdc
